parcheggiostrutturaLabels = {};
parcheggiostrutturaLabels['name'] = 'Nome';
parcheggiostrutturaLabels['streetReference'] = 'Indirizzo';
parcheggiostrutturaLabels['managementMode'] = 'Modalità di gestione';
parcheggiostrutturaLabels['slotNumber'] = 'Capienza';
parcheggiostrutturaLabels['timeSlot'] = 'Orari apertura';
parcheggiostrutturaLabels['paymentMode'] = 'Modalità pagamento';
parcheggiostrutturaLabels['phoneNumber'] = 'Telefono';
parcheggiostrutturaLabels['fee'] = 'Tariffe sosta';